spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/industrial_production_optimizer
spring.datasource.username=postgres
spring.datasource.password=3jjzufyi

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs