spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/industrial_production_optimizer
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.port=8080
server.error.include-stacktrace=never
server.error.include-message=never

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.profiles.active=local